### ISSUE TITLE
[DOC] Translate and Update Text in ReadMe Images from Portuguese BR to English

### ISSUE THREAD

**Issue by gustavostz** [EncodeDecodeStepByStep/EncodeDecodeStepByStep#2]
Our project's ReadMe features several key images containing text and captions in Portuguese (BR). To enhance accessibility for our international audience, we're seeking contributions to translate and update both the text within these images and their captions to English.

Here are a few examples of the images that require text and caption translation:

> ![Unary image in Portuguese BR](https://github.com/EncodeDecodeStepByStep/EncodeDecodeStepByStep/assets/48111506/a03a60ea-3113-46b3-bf36-d5204326e649)
> 
> ![Elias Gamma image in Portuguese BR](https://github.com/EncodeDecodeStepByStep/EncodeDecodeStepByStep/assets/48111506/f13024ef-2f48-4e9f-a3c8-bce1fcfd86df)
> 
> ![Huffman image in Portuguese BR](https://github.com/EncodeDecodeStepByStep/EncodeDecodeStepByStep/assets/48111506/c6ede8f0-09cf-45f7-b7ba-94b959b44bbf)
> 

This task involves identifying images with Portuguese text, translating the text to English, and editing the images to replace the original text. The goal is to maintain the clarity and integrity of the original images while ensuring the text is fully accessible in English.

This is a perfect 'good first issue' for new contributors, as it's an excellent way to familiarize yourself with the project without making direct code changes. Enhancing the ReadMe in this way is highly valuable; it's often the first point of interaction for users and potential contributors.

We welcome contributors to take up this task and support the community in making our documentation more inclusive and user-friendly. If you have any questions or need any help, feel free to ask me here. Your contributions are highly appreciated!

**Comment by UnwashedPine851** [comment]
Hello, I'd like to work on this issue!

**Comment by AMiracle-creator** [comment]
Hi, is this issue still open? I may try to do this as fast as i can!

**Comment by gustavostz** [comment]
@AMiracle-creator Yes, the @UnwashedPine851 opened a pull request, but has some small changes that I requested. You could use @UnwashedPine851 's pull request as a base or start from scratch, your choice :).

The PR that I requested the changes before approving is this: #3

**Comment by AMiracle-creator** [comment]
I don’t have time right now, I sincerely apologize for the inconvenience.

**Comment by gustavostz** [comment]
#3 done
